/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datastrct;

import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author mehdiarat
 */
public class PlayerCard extends javax.swing.JFrame {


     // playerCards değişkenini GameWindow sınıfında tanımladık

    /**
     * Creates new form PlayerCard
     */
    public PlayerCard() {
        initComponents();
        
    }
    
    public PlayerCard(int index){
        initComponents();
        showplayerCardsframe(index);
    }
    //paramettreli onstructor ekle

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridLayout(3, 9));

        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4);

        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2);

        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);

        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5);

        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);

        jLabel10.setText("jLabel10");
        jPanel3.add(jLabel10);

        jLabel7.setText("jLabel7");
        jPanel3.add(jLabel7);

        jLabel16.setText("jLabel16");
        jPanel3.add(jLabel16);

        jLabel17.setText("jLabel17");
        jPanel3.add(jLabel17);

        jLabel22.setText("jLabel22");
        jPanel3.add(jLabel22);

        jLabel21.setText("jLabel21");
        jPanel3.add(jLabel21);

        jLabel20.setText("jLabel20");
        jPanel3.add(jLabel20);

        jLabel19.setText("jLabel19");
        jPanel3.add(jLabel19);

        jLabel18.setText("jLabel18");
        jPanel3.add(jLabel18);

        jLabel15.setText("jLabel15");
        jPanel3.add(jLabel15);

        jLabel14.setText("jLabel14");
        jPanel3.add(jLabel14);

        jLabel13.setText("jLabel13");
        jPanel3.add(jLabel13);

        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6);

        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8);

        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9);

        jLabel11.setText("jLabel11");
        jPanel3.add(jLabel11);

        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    public void showplayerCardsframe(int playerIndex) {
    JFrame frame = new JFrame();
    frame.setTitle("Player " + playerIndex + "'s Cards");
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    JPanel panel = new JPanel(new GridLayout(3, 9)); // 3 satır, 9 sütunlu bir grid oluştur
    MultiLinkedList currentList = GameWindow.playerCards;
    for (int i = 1; i <= playerIndex; i++) {
        if (currentList == null) {
            // Belirtilen oyuncu numarasına sahip bir kart listesi yoksa hata mesajı yazdır ve geri dön
            System.out.println("Player " + playerIndex + " does not exist.");
            return;
        }
        currentList = currentList.next; // Bir sonraki oyuncunun kart listesine geç
    }

    if (currentList == null) {
        // Belirtilen oyuncu numarasına sahip bir kart listesi yoksa hata mesajı yazdır ve geri dön
        System.out.println("Player " + playerIndex + " does not exist.");
        return;
    }

    NodeClass current = currentList.head;
    while (current != null) {
        JLabel label = new JLabel();
        if (current.data == -1) {
            label.setText("X");
        } else {
            label.setText(Integer.toString(current.data));
        }
        panel.add(label); // Label'i panele ekle
        current = current.down; // Bir sonraki düğüme geç
    }

    frame.add(panel); // Paneli frame'e ekle
    frame.pack(); // Frame boyutunu ayarla
    frame.setVisible(true); // Frame'i görünür yap
}

    
    /*public void showplayerCardsframe (int playerIndex){
        
              

        MultiLinkedList currentList = GameWindow.playerCards;
        for (int i = 1; i <= playerIndex; i++) {
            if (currentList == null) {
                // Belirtilen oyuncu numarasına sahip bir kart listesi yoksa hata mesajı yazdır ve geri dön
                System.out.println("Player " + playerIndex + " does not exist.");
                return;
            }
            currentList = currentList.next; // Bir sonraki oyuncunun kart listesine geç
        }

        if (currentList == null) {
            // Belirtilen oyuncu numarasına sahip bir kart listesi yoksa hata mesajı yazdır ve geri dön
            System.out.println("Player " + playerIndex + " does not exist.");
            return;
        }

        // Belirtilen oyuncu numarasına sahip kart listesini bulduk
        // Bu listenin içeriğini yazdır
        currentList.printList2(this);
        

    }*/
    
        
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
